### PR TITLE
Update unordered list item marker

### PR DESCRIPTION
**Pull request by iamytg**
Debug an error where the counter contents also affect an unordered list.

### CODE REVIEW

**Comment by minimaluminium** [comment]
Hey @iamytg, really nice fix, thanks! Could you revert https://github.com/TryGhost/Alto/pull/24/commits/d2679d5f098682da5cc8319deca73ff47d3b13f5? The reason is we don't do releases for official themes except Casper. I'll be happy to merge it once it's updated :)

**Review by minimaluminium — CHANGES_REQUESTED** [review]
Hey @iamytg, really nice fix, thanks! Could you revert https://github.com/TryGhost/Alto/pull/24/commits/d2679d5f098682da5cc8319deca73ff47d3b13f5? The reason is we don't do releases for official themes except Casper. I'll be happy to merge it once it's updated :)

**Comment by iamytg** [comment]
@minimaluminium Okay, I did what you said. Thanks for your hard work.

**Comment by minimaluminium** [comment]
@iamytg Nice, thank you!

**Pull request merged**
